import { Montserrat } from "next/font/google";
import "./globals.css";
import Headers from "@/components/Headers";

const montserrat = Montserrat({
  weight: ["100" , "200", "300",  "400", "500", "600" , "700",  "900" ],
  subsets: ["latin"],
});

export const metadata = {
  title: "Le Reve | Leading Fasion And Lifestyle  Brand In Bangladesh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Headers />
        {children}</body>
    </html>
  );
}
